### ISSUE TITLE
Homebrew install instructions are out of date

### ISSUE THREAD

**Issue by bhaller** [MesserLab/SLiM#305]
This info from Martin Petr, @bodkan:

Not sure if this is useful, but I just put together a couple of notes on how to compile SLiM & SLiMgui on a fresh new M1 MacBook Pro that I got at work this week. It was very easy to do after tweaking the instructions provided in the SLiM manual but still, I suppose the section on Mac compilation using Homebrew has been written some time ago and perhaps updating the relevant paragraph might be useful?

Basically, the only changes I made to the compilation steps are those in which (I think) Homebrew simplified things quite a bit. In particular, manually creating symlinks is no longer needed and relevant PATH updates are suggested after installation of Homebrew itself (just for Qt, and just to get qmake on the $PATH). In other words, the prerequisites can be installed trivially with no additional work.

Here are the individual steps I just did on a brand new Monterey installation, copied in full from my personal Notes (I tested things both for the main branch and also for the multispecies branch—which was the main motivation for doing this).

If this is not useful or needed, feel free to ignore this. :) I could imagine there are more pressing updates needed for the documentation right now. :) It could very well be that the few people who want to get the development version compiled on a Mac for their own tweaking purposes will easily figure this out for themselves...

**Building SLiM on a brand new M1 Mac (macOS Monterey, version 12.3.1, 2022-04-14)**

Installed pre-requisites:

1. Install Xcode
2. Install Homebrew (https://brew.sh/)
3. brew install git (sudo no longer needed for Homebrew installations)
4. brew install cmake
5. brew install qt5

Make sure not to run brew install qt which installs Qt 6.x that’s not backwards compatible with what is needed (brew install qt5 currently gets us Qt 5.15.3 which is what we want).
According to Homebrew instructions shown after qt5 installation, this is needed to get qmake et al. on the $PATH:

	echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.profile

6. brew install qt-creator (note that this automatically creates /Applications/Qt Creator.app, so symlink is not needed)—this is not a "pre-requisite" per se, but nice to have anyway.

With all the above in place, everything can be compiled just as described in the SLiM manual:

1. git clone https://github.com/messerlab/SLiM (downloading a source code archive from GitHub would obviously work too)
2. Compiling slim and eidos binaries works with cmake & make commands exactly as presented in the SLiM manual
3. Compiling SLiMgui with with qmake & make exactly the same as well (and the result can be executed from ./QtSLiM/SLiMgui.app/Contents/MacOS/SLiMgui). Same goes for opening the SLiM project in Qt Creator.

**Comment by bhaller** [comment]
OK, I edited that bit to say this:

> If you are a Homebrew user, the package named `qt5` currently provides Qt 5.15.3; do not use the `qt` package, as that will install Qt 6, which you do not want.  The command would thus be `brew install qt5`; using `sudo` should not be needed, but if the install fails due to permissions then try `sudo brew install qt5`.  You can get `qmake` on your `$PATH` (so Terminal can find it) after this install by doing `echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.profile` or, alternatively, you can set up a symlink to it with `sudo brew link qt5 —force`, or if that doesn’t work, `sudo ln -s /usr/local/Cellar/qt/<QT_VERSION_HERE>/bin/qmake /usr/local/bin/qmake`.  If you want the Qt Creator IDE as well (perhaps to run SLiMgui under the debugger), you should be able to install it with `brew install qt-creator` and a link to it in your `/Applications` folder should be created by Homebrew automatically.  (You probably also want to do `brew install git` to install `git`, and `brew install cmake` to get `cmake`; both may be needed below.)

I'm hesitant to remove all of the old instructions, since it seems like the sands are always shifting with this stuff and instructions that work one day don't work the next (which is frustrating).  If a given instruction doesn't work for someone, I want to try to provide a trail of bread crumbs that help them find their way.  I realize that makes the instructions harder to read, but it saves a lot of headaches in the long term, I think.  In fact, I would not be at all surprised to learn that the install steps that worked for you still don't work correctly for a user on, say, macOS 10.13 (and lots of people are still back there).

Closing this issue for now, but if you think further edits are needed, reopen or start a new one.  Thanks!

**Comment by bodkan** [comment]
Hello @bhaller, I think this is great. This is all the info that any user who wishes to compile SLiM on the latest macOS should need. 

Thank you!

[I also agree that removing the old instructions would've been a bad idea at this point.]

**Comment by bhaller** [comment]
> Hello @bhaller, I think this is great. This is all the info that any user who wishes to compile SLiM on the latest macOS should need.

Well, that would be nice; but there's people who don't use Homebrew (I use Macports), people who don't use either, people who don't know how to use the command line... :->  Installation just turns out to be an incredibly ugly and complicated topic, and I don't think that's going to change.  There's conda, there's computing clusters, there's people running ancient OS versions who for one reason or another can't upgrade.  And then there are all the mysterious build failures that happen for just one person, and you can't figure out why.  And there's building with Xcode versus cmake versus qmake.  And... well, you get the point.  :->

> Thank you!

What I'm here for.  :->  Thank you!

**Comment by bodkan** [comment]
Haha, yes, of course! I wanted to say _"This is all the info that any **Homebrew** user who wishes to compile SLiM on the latest macOS should need."_ :)

**Comment by bhaller** [comment]
I was loosely following all of the agonizing python install issues you were battling against recently.  It made me glad that I didn't try to make SLiM a Python package.  :->  There is often pushback from people against the idea of having to learn Eidos – yet another programming language, really?  And I totally get that.  But I think it's one of the best decisions I made with SLiM.  If only I could write the SLiM core in Eidos, and leave behind C/C++ completely.  :->

**Comment by bodkan** [comment]
> I was loosely following all of the agonizing python install issues you were battling against recently.

OMG. That was crazy. I pushed out the preprint, went to bed all excited about what's next... And then I wake up to see two slendr GitHub issues and one email... all boiling down to Python setup/installation issues that had nothing to do with R or SLiM. :D The despair... Came back stronger though. :) 

 > There is often pushback from people against the idea of having to learn Eidos – yet another programming language, really? And I totally get that. But I think it's one of the best decisions I made with SLiM.

I 100% agree. _Very_ early on I was one of those people and felt it would've been so much better to use an established language (and SLiM and I go [waaay back](https://github.com/MesserLab/SLiM/issues/2) -- GitHub issue #2! :)) but I quickly learned to appreciate everything that Eidos does. And I'm talking only about the language, not even about the super tight integration with SLiMgui, the interactive help browsing, autocomplete... Only heavily customized and/or proprietary professional Python IDEs have something similar.

> If only I could write the SLiM core in Eidos, and leave behind C/C++ completely. :->

Totally unrelated, but the other day I've been thinking about how fun would it be to learn a bit more about compilers and low-level stuff. Found some tutorials on building languages on top of LLVM and thought about implementing a tiny toy R/Eidos-like language... and then looked at my TODO list and promtly dropped the idea (for now).

**Comment by bhaller** [comment]
Issue #2, I had forgotten that!  :->  I'm glad you're an Eidos convert, that's reassuring.  I still get lots of complaints about it, but I stick to my guns.

Some time you ought to poke around with language design, yeah; it's really fun.  Designing and developing Eidos was a blast.  And hey, if you want to real-world project in that area: I have been thinking that providing a way to do "just in time" compilation of Eidos script for greater efficiency, at least down to a byte-code format if not all the way to machine code, would be pretty cool.  I don't think I'll ever have time to do it, but if you ever want to get a second PhD in CS, it might be a good project.  :->
